### ISSUE TITLE
他の人の環境下でファイルが消去されない

### ISSUE THREAD

**Issue by Rick-Kota** [Rick-Kota/Slack_file_Delete#1]
他の人の環境下でファイルが消去されず、表示がループしている
尚、自分の環境下では連続３個の消去までしか行っていないのでそこら辺に問題が隠れているのかもしれない

**Comment by Rick-Kota** [comment]
実行者がアップロードしたファイルは消去さてている模様
管理者以外が実行したことによる問題の可能性が浮上

**Comment by Takuya76007** [comment]
私が試したところ、My Filesのものは消えました
ループの原因はわかりませんが、if文で消去ファイル数数えて、取得したファイル数文になったら終了すれば良いかと。

**Comment by Takuya76007** [comment]
24行目？
while 1:→無限ループでは？

**Comment by Rick-Kota** [comment]
先ほど実験したところ
管理者権限の問題であるとわかりました

ファイルリストが、自身がオーナーでない（=消去権限がない）ファイルもリストに読み込むのに対して
消去コマンドが受け付けるのが自身がオーナーのファイルのみのため
最終的に権限のないファイルがなくならずループが発生している模様です

**Comment by Rick-Kota** [comment]
解決策としてはDMの問題があるので
全員が一時的に管理者になるか
ファイルリストをユーザーでフィルタを掛けることが考えられます

運用時の簡単を考えると後者が良いと思います

原因がわかったため閉じます
